#!/system/bin/sh
#Governor
#Change CPU governor:
#ZZMoove

# boeffla tweaks app init.d script for zzmoove governor version 0.5

# switch governor only if it is not loaded already
if [ ! `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor | /sbin/busybox grep zzmoove` ]; then
echo "zzmoove" >/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
fi;

# zzmoove governor default settings (also hardcoded):
echo "100000" >/sys/devices/system/cpu/cpufreq/zzmoove/sampling_rate
echo "4" >/sys/devices/system/cpu/cpufreq/zzmoove/sampling_rate_sleep_multiplier
echo "1" >/sys/devices/system/cpu/cpufreq/zzmoove/sampling_down_factor
echo "0" >/sys/devices/system/cpu/cpufreq/zzmoove/sampling_down_max_momentum
echo "50" >/sys/devices/system/cpu/cpufreq/zzmoove/sampling_down_momentum_sensitivity
echo "70" >/sys/devices/system/cpu/cpufreq/zzmoove/up_threshold
echo "100" >/sys/devices/system/cpu/cpufreq/zzmoove/up_threshold_sleep
echo "75" >/sys/devices/system/cpu/cpufreq/zzmoove/smooth_up
echo "100" >/sys/devices/system/cpu/cpufreq/zzmoove/smooth_up_sleep
echo "68" >/sys/devices/system/cpu/cpufreq/zzmoove/up_threshold_hotplug1
echo "68" >/sys/devices/system/cpu/cpufreq/zzmoove/up_threshold_hotplug2
echo "68" >/sys/devices/system/cpu/cpufreq/zzmoove/up_threshold_hotplug3
echo "52" >/sys/devices/system/cpu/cpufreq/zzmoove/down_threshold
echo "60" >/sys/devices/system/cpu/cpufreq/zzmoove/down_threshold_sleep
echo "55" >/sys/devices/system/cpu/cpufreq/zzmoove/down_threshold_hotplug1
echo "55" >/sys/devices/system/cpu/cpufreq/zzmoove/down_threshold_hotplug2
echo "55" >/sys/devices/system/cpu/cpufreq/zzmoove/down_threshold_hotplug3
echo "0" >/sys/devices/system/cpu/cpufreq/zzmoove/disable_hotplug
echo "1" >/sys/devices/system/cpu/cpufreq/zzmoove/hotplug_sleep
echo "5" >/sys/devices/system/cpu/cpufreq/zzmoove/freq_step
echo "1" >/sys/devices/system/cpu/cpufreq/zzmoove/freq_step_sleep
echo "0" >/sys/devices/system/cpu/cpufreq/zzmoove/freq_limit
echo "700000" >/sys/devices/system/cpu/cpufreq/zzmoove/freq_limit_sleep
echo "0" >/sys/devices/system/cpu/cpufreq/zzmoove/fast_scaling
echo "0" >/sys/devices/system/cpu/cpufreq/zzmoove/fast_scaling_sleep
echo "0" >/sys/devices/system/cpu/cpufreq/zzmoove/early_demand
echo "25" >/sys/devices/system/cpu/cpufreq/zzmoove/grad_up_threshold
echo "0" >/sys/devices/system/cpu/cpufreq/zzmoove/ignore_nice_load
echo "0" >/sys/devices/system/cpu/cpufreq/zzmoove/lcdfreq_enable
echo "0" >/sys/devices/system/cpu/cpufreq/zzmoove/lcdfreq_kick_in_cores
echo "50" >/sys/devices/system/cpu/cpufreq/zzmoove/lcdfreq_kick_in_up_delay
echo "20" >/sys/devices/system/cpu/cpufreq/zzmoove/lcdfreq_kick_in_down_delay
echo "500000" >/sys/devices/system/cpu/cpufreq/zzmoove/lcdfreq_kick_in_freq
