#!/system/bin/sh
#Settings: Backup current settings
#Backup current settings of Boeffla-Tweaks app

TITLE="Backup current settings"
STYLE="Ok"

SETTINGSFILE="/sdcard/boeffla-kernel-data/settingsbackup"

# Ask for confirmation
rm /sdcard/boeffla_twk_dlg_helper
am start -a android.intent.action.MAIN -e message "Do you really want to backup your current settings?" -e title "$TITLE" -e button1 "Yes" -e button2 "No" -e toasty "Backup settings now!" -e toastn "Backup settings aborted!" -n bo.boeffla.tweaks.dialog.helper/.BoefflaTweaksDialogActivity

while [ ! -f /sdcard/boeffla_twk_dlg_helper ]
do
  /sbin/busybox sleep 1
done

RESULT=`cat /sdcard/boeffla_twk_dlg_helper`

if [ "$RESULT" = "yes" ]; then

	# Backup current settings
	/sbin/busybox find /system/etc/init.d -name '*_???bk*' > $SETTINGSFILE

	# Display confirmation window
	rm /sdcard/boeffla_twk_dlg_helper
	am start -a android.intent.action.MAIN -e message "Your settings have been saved. You can restore them any time by using the restore function!" -e title "$TITLE" -e okstyle "$STYLE" -n bo.boeffla.tweaks.dialog.helper/.BoefflaTweaksDialogActivity

	while [ ! -f /sdcard/boeffla_twk_dlg_helper ]
	do
	  /sbin/busybox sleep 1
	done

fi

rm /sdcard/boeffla_twk_dlg_helper
