#!/system/bin/sh
#Config: Delete boeffla-kernel.conf
#Deletes the boeffla-kernel.conf file (next start will create new standard config file)

TITLE="Config: Delete boeffla-kernel.conf"
STYLE="Ok"

if [ -f /sdcard/boeffla_twk_dlg_helper ]; then
  rm /sdcard/boeffla_twk_dlg_helper
fi;

am start -a android.intent.action.MAIN -e message "Do you really want to delete boeffla-kernel.conf?" -e title "$TITLE" -e button1 "Yes" -e button2 "No" -e toasty "Deleting boeffla-kernel.conf now!" -e toastn "Delete of boeffla-kernel.conf aborted!" -n bo.boeffla.tweaks.dialog.helper/.BoefflaTweaksDialogActivity

while [ ! -f /sdcard/boeffla_twk_dlg_helper ]
do
  /sbin/busybox sleep 1
done

RESULT=`cat /sdcard/boeffla_twk_dlg_helper`

if [ "$RESULT" = "yes" ]; then

  if [ -f /sdcard/boeffla_twk_dlg_helper ]; then
    rm /sdcard/boeffla_twk_dlg_helper
  fi;

  /sbin/busybox rm /data/media/boeffla-kernel/boeffla-kernel.conf

am start -a android.intent.action.MAIN -e message "Delete boeffla-kernel.conf file done! Next start will create new standard config file." -e title "$TITLE" -e okstyle "$STYLE" -n bo.boeffla.tweaks.dialog.helper/.BoefflaTweaksDialogActivity

else
  if [ -f /sdcard/boeffla_twk_dlg_helper ]; then
    rm /sdcard/boeffla_twk_dlg_helper
  fi;
  exit 0
fi;
